### ISSUE TITLE
DynamicLauncherProxy prepare_install method does not forward correct argument type for Icon param

### ISSUE THREAD

**Issue by andreibachim** [bilelmoussaoui/ashpd#158]
### Description
The [prepare_install](https://docs.rs/ashpd/latest/ashpd/desktop/dynamic_launcher/struct.DynamicLauncherProxy.html#method.prepare_install) function of the DynamicLauncherProxy does not send the correct type for the icon parameter. The portal [expects a variant](https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-method-org-freedesktop-portal-DynamicLauncher.PrepareInstall), the method sends a struct(string, variant).

### Setup
Used version: `0.6.2`

### Evidence
Full error: 
```
Err(
    Zbus(
        MethodError(
            OwnedErrorName(
                ErrorName(
                    Str(
                        Owned(
                            "org.freedesktop.DBus.Error.InvalidArgs",
                        ),
                    ),
                ),
            ),
            Some(
                "Type of message, “(ss(sv)a{sv})”, does not match expected type “(ssva{sv})”",
            ),
            Msg {
                type: Error,
                sender: UniqueName(
                    Str(
                        Borrowed(
                            ":1.62",
                        ),
                    ),
                ),
                reply-serial: 5,
                body: Signature(
                    "s",
                ),
            },
        ),
    ),
)
```

Method call inspected using dbus-monitor:

```
method call time=1693151827.422401 sender=:1.2558 -> destination=org.freedesktop.portal.Desktop serial=5 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.DynamicLauncher; member=PrepareInstall
   string ""
   string "My App"
   struct {
      string "themed"
      variant          array [
            string "dialog-symbolic"
         ]
   }
   array [
      dict entry(
         string "handle_token"
         variant             string "ashpd_MuJSQUqAo2"
      )
      dict entry(
         string "launcher_type"
         variant             uint32 1
      )
   ]
error time=1693151827.422665 sender=:1.62 -> destination=:1.2558 error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=5
   string "Type of message, “(ss(sv)a{sv})”, does not match expected type “(ssva{sv})”"

```

**Comment by bilelmoussaoui** [comment]
I think the problem comes from the parentheses in #[zvariant(signature = "(sv)")] for Icon type. Can you try a fork of ashpd without them and see if that helps?

**Comment by andreibachim** [comment]
It doesn't work. Actually, it also breaks notifications portal, which also uses the Icon type and works fine with the current implementation.

I have change to line to `#[zvariant(signature = "sv")]` and this is the error I get

```
Err(
    Portal(
        ZBus(
            Variant(
                Message(
                    "invalid type: character `s`, expected `(` or `{`",
                ),
            ),
        ),
    ),
)
```

**Comment by bilelmoussaoui** [comment]
Hmm. I will see what can i do later today

**Comment by bilelmoussaoui** [comment]
Can you try with the patch in https://github.com/bilelmoussaoui/ashpd/pull/159?

**Comment by bilelmoussaoui** [comment]
I pushed a different solution in a second commit. So when testing, please try the first commit, if it works great, if it doesn't try the 2nd one.

**Comment by andreibachim** [comment]
The initial error regarding the invalid parameter type is no longer occurring. 

However, I still cannot get the feature to work, though I am not entirely sure I got the vector of bytes correctly. Please let me know if this is not correct. Here is how I got the vector:

```rust
let f = File::open("godot.png")?;
let mut reader = BufReader::new(f);
let mut buffer = Vec::new();

...

let (name, token) = proxy.prepare_install(
    &WindowIdentifier::default(),
    "My App",
    Icon::Bytes(buffer),
    PrepareInstallOptions::default(),
).await?.response()?;
```

The error I get is
```
Err(
    Zbus(
        MethodError(
            OwnedErrorName(
                ErrorName(
                    Str(
                        Owned(
                            "org.freedesktop.portal.Error.InvalidArgument",
                        ),
                    ),
                ),
            ),
            Some(
                "Dynamic launcher icon failed validation",
            ),
            Msg {
                type: Error,
                sender: UniqueName(
                    Str(
                        Borrowed(
                            ":1.62",
                        ),
                    ),
                ),
                reply-serial: 5,
                body: Signature(
                    "s",
                ),
            },
        ),
    ),
)

```

The second commit return the same error when using Icon::Bytes variant, and it still refuses to accept any other variant (from code from the first commit).

**Comment by bilelmoussaoui** [comment]
Ok, thanks for testing. This time I will actually test it and add it to the demo page instead of randomly guessing the error.
